models:
  segmentation_tflite: "trained_models/segmentation/exported/segmentation_model_final.tflite" 
  classification_tflite: "trained_models/classification/exported/classification_model_final.tflite" 
  segmentation_model: "models/segmentation/segmentation_model_final.tflite"
  segmentation_config: "models/segmentation/config.yaml"
  classification_config: "models/classification/config.yaml" 

model_params:
  segmentation_input_size: [256, 256] 
  segmentation_num_classes: 1 
  segmentation_threshold: 0.5 # Threshold for converting probabilities to binary mask
  classification_input_size: [224, 224] 
  classification_labels: "trained_models/classification/exported/label_map.json" 
  classification_confidence_threshold: 0.6

camera_intrinsics:
  default: 
    width: 1920
    height: 1440
    fx: 1575.0  
    fy: 1575.0  
    cx: 958.5   # (1920 / 2 - 0.5)
    cy: 718.5   # (1440 / 2 - 0.5)
  "1024x1024": 
    width: 1024
    height: 1024
    fx: 1120.42 
    fy: 1120.42 
    cx: 511.5   # (1024 / 2 - 0.5)
    cy: 511.5   # (1024 / 2 - 0.5)
  "640x480":  
    width: 640
    height: 480
    fx: 525.0   
    fy: 525.0   
    cx: 319.5   # (640 / 2 - 0.5)
    cy: 239.5   # (480 / 2 - 0.5)
  "1280x720":
    width: 1280
    height: 720
    fx: 960.0   # HD resolution scaling
    fy: 960.0
    cx: 639.5   # (1280 / 2 - 0.5)
    cy: 359.5   # (720 / 2 - 0.5)
  "1440x1920":
    width: 1440
    height: 1920
    fx: 1181.25
    fy: 1181.25
    cx: 719.5   # (1440 / 2 - 0.5)
    cy: 959.5   # (1920 / 2 - 0.5)

volume_estimation:
  default_intrinsics_key: "default"
  processing_params:
    depth_scale: 1000.0           # Depth values in mm
    depth_trunc_m: 3.0            # Truncate depth beyond 3 meters
    project_valid_depth_only: true
    downsample_voxel_size_m: 0.005  # 5mm voxel size for downsampling
    outlier_removal_nb_neighbors: 20
    outlier_removal_std_ratio: 2.0
    volume_voxel_size_m: 0.005    # 5mm voxel size for volume calculation

volume_params:
  min_depth_m: 0.1
  max_depth_m: 1.5 
  depth_scale_factor: 1000.0

# Centralized path configuration for modularity
paths:
  # Config file paths
  classification_config: "models/classification/config.yaml"
  segmentation_config: "models/segmentation/config.yaml"
  pipeline_config: "config_pipeline.yaml"
  
  # Script paths
  prepare_classification_script: "scripts/prepare_classification_dataset.py"
  prepare_segmentation_script: "scripts/prepare_segmentation_metadata.py"
  train_classification_script: "models/classification/train.py"
  train_segmentation_script: "models/segmentation/train.py"
  export_classification_tflite_script: "models/classification/export_tflite.py"
  export_segmentation_tflite_script: "models/segmentation/export_tflite.py"
  
  # Model directories
  classification_model_dir: "trained_models/classification"
  segmentation_model_dir: "trained_models/segmentation"
  classification_export_dir: "trained_models/classification/exported"
  segmentation_export_dir: "trained_models/segmentation/exported"
  
  # Data directories
  classification_meta_dir: "data/classification"
  segmentation_meta_dir: "data/segmentation"
